# Generated by Django 3.1.7 on 2022-02-25 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaVariation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('so', 'Social Profile'), ('ph', 'Phone Number')], default='so', max_length=2)),
                ('share_type', models.CharField(choices=[('username', 'Username'), ('telephone #', 'Telephone'), ('url', 'Url')], default='username', max_length=20)),
                ('share_type_display', models.CharField(choices=[('username', 'Username'), ('telephone #', 'Telephone'), ('url', 'Url'), ('username or telephone', 'Username or Telephone')], default='username', max_length=40)),
                ('share_action_type', models.CharField(choices=[('ol', 'Open Link'), ('cp', 'Copy'), ('cl', 'Copy if phone number and link if username')], default='ol', max_length=2)),
                ('share_action_data_format', models.CharField(max_length=100)),
                ('bright_id_app_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('test', 'test'), ('node', 'node')], default='node', max_length=20)),
                ('bright_verification_status', models.CharField(choices=[('0', 'Pending'), ('1', 'Verified')], default='0', max_length=1)),
                ('profile', models.CharField(max_length=255)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_medias', to='core.socialmediavariation')),
            ],
        ),
    ]
