# Generated by Django 3.1.7 on 2022-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
