# Generated by Django 3.1.7 on 2022-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialmedia_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediavariation',
            name='type',
            field=models.CharField(choices=[('so', 'Social Profile'), ('co', 'Contact Info')], default='so', max_length=2),
        ),
    ]
