# Generated by Django 3.1.7 on 2022-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220305_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
