# Generated by Django 3.1.7 on 2022-03-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220306_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='profile',
        ),
        migrations.CreateModel(
            name='ProfileHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_hashes', to='core.socialmedia')),
            ],
        ),
    ]
