# Generated by Django 3.1.7 on 2022-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220312_1735'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profilehash',
            index=models.Index(fields=['value'], name='core_profil_value_7f3cc4_idx'),
        ),
    ]
